### ISSUE TITLE
Error running jhipster-grpc

### ISSUE THREAD

**Issue by jgagnon44** [cbornet/generator-jhipster-grpc#26]
OS: CentOS 7
Java: OpenJDK 11
JHipster: 6.4.1
npm: 6.11.3

Installed generator-jhipster-grpc via npm:
> npm install generator-jhipster-grpc

In a project folder containing an existing JHipster microservice project, attempted to run jhipster-grpc:
> yo jhipster-grpc

? ==========================================================================
We're constantly looking for ways to make yo better! 
May we anonymously report usage statistics to improve the tool over time? 
More info: https://github.com/yeoman/insight & http://yeoman.io
========================================================================== No
events.js:187
      throw er; // Unhandled 'error' event
      ^

TypeError: this.getJhipsterAppConfig is not a function
    at module.exports.readConfig (/home/jgagnon/node_modules/generator-jhipster-grpc/generators/app/index.js:19:47)
    at Object.<anonymous> (/home/jgagnon/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:424:27)
    at /home/jgagnon/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /home/jgagnon/node_modules/run-async/index.js:24:19
    at /home/jgagnon/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:425:13
    at processImmediate (internal/timers.js:439:21)
Emitted 'error' event on Generator instance at:
    at Immediate.<anonymous> (/home/jgagnon/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:433:22)
    at processImmediate (internal/timers.js:439:21)

**Comment by cbornet** [comment]
Yes, this is a duplicate of #25. The module isn't compatible with recent Jhipster versions. I need to do the upgrade. Help through PR is very welcome.

**Comment by jgagnon44** [comment]
Christophe,

Could you give me an idea of an older version of JHipster that your
generator works with?

Do you have an idea of whether the updates are something you have planned
for the near future, or if it will be longer out?

Do you have an idea of what needs to be done to get jhipster-grpc
compatible with the current JHipster? Do you think it's involved or could
it be a relatively simple fix?

I'm thinking I may clone your code from github and see what I can learn.
Perhaps I can figure it out and let you know.

Thanks,
Joe Gagnon

**Comment by cbornet** [comment]
The master works with v5.0. It may work with some upper versions. I don't know when it broke. I do intend to update the module for newer versions. I also have some ideas for improvements (use armeria, support reactive,...)

**Comment by jgagnon44** [comment]
Christophe,

I removed the latest version of JHipster and installed version 5.0.0. I
then installed your latest version of the gRPC generator, but there were
some issues during the installation.

I decided to push on and see if I could get further.


*I'm wondering whether I need to downgrade my versions for npm and/or node?
Or is there some other problem?*

Below are snippets from the console of my attempts to install and execute.
Apologies for the amount of information.

*Current versions:*

[jgagnon@centos7-1 ~]$ java -version
openjdk version "11.0.4" 2019-07-16 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.4+11-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.4+11-LTS, mixed mode, sharing)

[jgagnon@centos7-1 ~]$ mvn -v
Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117;
2019-08-27T11:06:16-04:00)
Maven home: /home/jgagnon/applications/apache-maven-3.6.2
Java version: 11.0.4, vendor: Oracle Corporation, runtime:
/usr/lib/jvm/java-11-openjdk-11.0.4.11-1.el7_7.x86_64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-1062.1.2.el7.x86_64", arch: "amd64",
family: "unix"

[jgagnon@centos7-1 ~]$ npm -v
6.12.0
[jgagnon@centos7-1 ~]$ node -v
v12.13.0
[jgagnon@centos7-1 ~]$ yo --version
3.1.0

*Install JHipster 5.0.0:*

[jgagnon@centos7-1 ~]$ sudo npm install -g generator-jhipster@5.0.0
/usr/bin/jhipster ->
/usr/lib/node_modules/generator-jhipster/cli/jhipster.js

> spawn-sync@1.0.15 postinstall
/usr/lib/node_modules/generator-jhipster/node_modules/spawn-sync
> node postinstall

+ generator-jhipster@5.0.0
added 465 packages from 308 contributors in 45.454s
[jgagnon@centos7-1 ~]$ jhipster --version
Using JHipster version installed globally
5.0.0

*Install generator-jhipster-grpc:*

[jgagnon@centos7-1 ~]$ sudo npm install -g generator-jhipster-grpc
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires
a build toolchain, use it instead

> core-js@3.3.3 postinstall
/usr/lib/node_modules/generator-jhipster-grpc/node_modules/core-js
> node postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for
polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open
Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for
a good job -)


> spawn-sync@1.0.15 postinstall
/usr/lib/node_modules/generator-jhipster-grpc/node_modules/spawn-sync
> node postinstall


> yo@3.1.0 postinstall
/usr/lib/node_modules/generator-jhipster-grpc/node_modules/yo
> yodoctor


Yeoman Doctor
Running sanity checks on your system

✔ No .bowerrc file in home directory
✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ No .yo-rc.json file in home directory
✔ Node.js version
✔ npm version
ErrorClass [RequestError]: connect ETIMEDOUT 104.16.25.35:443
    at ClientRequest.<anonymous>
(/usr/lib/node_modules/generator-jhipster-grpc/node_modules/latest-version/node_modules/got/index.js:73:21)
    at Object.onceWrapper (events.js:300:26)
    at ClientRequest.emit (events.js:210:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ETIMEDOUT',
  message: 'connect ETIMEDOUT 104.16.25.35:443',
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  method: 'GET',
  path: '/yo'
}
✖ yo version
ErrorClass [RequestError]: connect ETIMEDOUT 104.16.25.35:443
    at ClientRequest.<anonymous>
(/usr/lib/node_modules/generator-jhipster-grpc/node_modules/latest-version/node_modules/got/index.js:73:21)
    at Object.onceWrapper (events.js:300:26)
    at ClientRequest.emit (events.js:210:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ETIMEDOUT',
  message: 'connect ETIMEDOUT 104.16.25.35:443',
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  method: 'GET',
  path: '/yo'
}

Found potential issues on your machine :(
+ generator-jhipster-grpc@0.15.2
added 826 packages from 415 contributors in 936.716s

[jgagnon@centos7-1 ~]$ yo jhipster-grpc --version
3.1.0

I then created a microservice by running jhipster. I then tried to run the
gRPC generator:

[jgagnon@centos7-1 test_jhip_micro]$ yo jhipster-grpc
events.js:187
      throw er; // Unhandled 'error' event
      ^

TypeError: this.getJhipsterAppConfig is not a function
    at module.exports.readConfig
(/usr/lib/node_modules/generator-jhipster-grpc/generators/app/index.js:19:47)
    at Object.<anonymous>
(/usr/lib/node_modules/generator-jhipster-grpc/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:424:27)
    at
/usr/lib/node_modules/generator-jhipster-grpc/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at
/usr/lib/node_modules/generator-jhipster-grpc/node_modules/run-async/index.js:24:19
    at
/usr/lib/node_modules/generator-jhipster-grpc/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:425:13
    at processImmediate (internal/timers.js:439:21)
Emitted 'error' event on Generator instance at:
    at Immediate.<anonymous>
(/usr/lib/node_modules/generator-jhipster-grpc/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:433:22)
    at processImmediate (internal/timers.js:439:21)

**Comment by cbornet** [comment]
Did you clone the module project or install from npm. It would only work by cloning atm.

**Comment by jgagnon44** [comment]
I installed it via npm

**Comment by jgagnon44** [comment]
I assume you mean that I need to clone your gRPC generator and not JHipster
itself? In any case, what do I do with the cloned distribution to "install"
it?

**Comment by jgagnon44** [comment]
Christophe,

First, let me apologize for posting this in this venue. However, I don't know how else to make contact with you.

I need some help to understand a project generated by JHipster (it's structure and what the various components that are generated are for). Once the application has been generated, I'm not sure what to do next. I don't know what components need to be written or where they should be placed. The JHipster web site has a lot of helpful information, but I have not been able to figure out how to take it to the next level.

Similarly, when I use the gRPC generator, it's not clear what it does to the existing generated app. I'm not sure what I need to do in order for it to "gRPC-icize" the application. I've tried running on a microservice app I had JHipster generate, but it didn't seem to have done anything. Evidently, it's missing something I need to provide - but I don't know what that is.

There is mention of entities with a service association, but I'm not sure what that translates into as far as artifacts that must be provided. I've written some simple gRPC services with simple test message types manually and understand what's happening, but have no idea what I need to put in place so that JHipster and the gRPC generator will produce the appropriate gRPC-specific code.

I downloaded your sample JHipster-gRPC app, but am having a maven build issue (see an issue I entered on that project) that is blocking me. Aside from that it would be helpful if there was some documentation describing the features being implemented and then being generated by the gRPC generator. I don't see anything that helps to explain this.

**Comment by cbornet** [comment]
Hi. A Jhipster app is just a standard Spring boot app. So if you understand Spring boot well, you shouldn't have any problem with Jhipster. Our motto is to generate for you what you would have written by hand. It's kind of the same for this module. It generates the same gRPC endpoints as the HTTP/REST ones you get with a standard JH app. If you give more details on what you're trying to achieve, I may be able to give more help.

**Comment by jgagnon44** [comment]
> TypeError: this.getJhipsterAppConfig is not a function
> at module.exports.readConfig (/home/jgagnon/node_modules/generator-jhipster-grpc/generators/app/index.js:19:47)

Apparently the function name changed to getAllJhipsterConfig. If I make this change in the indicated file, the problem is resolved and I can proceed further.

**Comment by jgagnon44** [comment]
Now that I've been able to get further, I'm running into further issues. I'm guessing it's a high probability because of the fact that the gRPC generator is not currently compatible with JHipster 6 (and perhaps other libraries?).

As an example, running mnvw now produces compilation errors for some of the "built-in" services you generate (e.g. MetricService). I briefly inspected this code and discovered that a Spring Boot class (`org.springframework.boot.actuate.metrics.PublicMetrics`) cannot be found. I suspect that somewhere along the evolution of Spring Boot that either the class was removed, renamed or placed someplace else.

```
[ERROR] /C:/Users/JO24447/eclipse-workspace/test-jhip-3/src/main/java/edu/mit/ll/alisn/exp/grpc/MetricService.java:[5,48] cannot find symbol         
[ERROR]   symbol:   class PublicMetrics                                                                                                              
[ERROR]   location: package org.springframework.boot.actuate.metrics                                                                                 
[ERROR] /C:/Users/JO24447/eclipse-workspace/test-jhip-3/src/main/java/edu/mit/ll/alisn/exp/grpc/MetricService.java:[18,24] cannot find symbol        
[ERROR]   symbol:   class PublicMetrics                                                                                                              
[ERROR]   location: class edu.mit.ll.alisn.exp.grpc.MetricService                                                                                    
[ERROR] /C:/Users/JO24447/eclipse-workspace/test-jhip-3/src/main/java/edu/mit/ll/alisn/exp/grpc/MetricService.java:[25,37] cannot find symbol        
[ERROR]   symbol:   class PublicMetrics                                                                                                              
[ERROR]   location: class edu.mit.ll.alisn.exp.grpc.MetricService                                                                                    
```

With these difficulties in mind, what would you suggest I try to do? Should I switch to the older version (5.0.0) of JHipster that *should* work?

You had mentioned in an earlier reponse that I would need to clone (rather than npm install) your generator for that to work. Since this not the "standard" way to install it, what do I need to do with the cloned generator to fold it into everything else?

**Comment by cbornet** [comment]
Yes this module hasn't been upgraded to JH6 at the moment. The master branch is known to work with JH5.0, Java8 and node 8. I have begun to make the upgrade since there is demand for that. Stay tuned !

**Comment by cbornet** [comment]
FYI version 0.16.0 was just released which works for JH 5.0 to 5.7. (tested OK with node 10)
