### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by gmarziou** [cbornet/generator-jhipster-grpc#11]
Hi Christophe,

Just tried quickly your module and I have compilation errors.
Did you test with DTOs?

https://github.com/gmarziou/grpc-serv2.git

```
[ERROR] /Users/gael/jhipster/projets/grpc/serv2/src/test/java/com/mycompany/myapp/grpc/entity/book/BookGrpcServiceIntTest.java:[108,37] cannot find symbol
  symbol:   method bookToBookDTO(com.mycompany.myapp.domain.Book)

```
what I did

```
mkdir serv2
cd serv2
yarn link generator-jhipster
yarn link generator-jhipster-grpc
yo jhipster
yo jhipster:entity Book
yo jhipster-grpc
yo jhipster:entity Book
./mvnw
```

I'm away from home so not in best conditions to debug.

##### **Browsers and Operating System**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.10.1 (Apple Git-78)

node: v6.10.0

npm: 3.10.10

yeoman: 1.8.5

yarn: 0.23.4

**Comment by cbornet** [comment]
The main generator master has incompatible changes.
I try to keep the master of this module working with the latest release only.
Can you try with generator-jhipster@4.3.0 ?

**Comment by gmarziou** [comment]
Thanks, It works with 4.3.0:

    gRPC Server started, listening on port 6565.

Is there a way to configure the port?

What do you use for interactive testing?

I have seen https://github.com/njpatel/grpcc

**Comment by cbornet** [comment]
I didn't know about grpcc. Looks nice !
For now I mostly did TDD. I'll integrate the [gRPC gateway](https://github.com/grpc-ecosystem/grpc-gateway) asap to get back the ease of use of REST in dev.
